disk = "boson"
primarys = ["gamma", "proton", "helium", "nitrogen", "aluminium", "iron"]

bins = {
    "gamma": [
        "01",
        "02",
        "03",
        "04",
        "05",
        "06",
        "07",
        "08",
        "09",
        "10",
        11,
        12,
        13,
        14,
        15,
    ],
    "proton": [
        "01",
        "02",
        "03",
        "04",
        "05",
        "06",
        "07",
        "08",
        "09",
        "10",
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
    ],
    "helium": [
        "01",
        "02",
        "03",
        "04",
        "05",
        "06",
        "07",
        "08",
        "09",
        "10",
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
    ],
    "nitrogen": [
        "03",
        "04",
        "05",
        "06",
        "07",
        "08",
        "09",
        "10",
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
    ],
    "aluminium": [
        "04",
        "05",
        "06",
        "07",
        "08",
        "09",
        "10",
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
    ],
    "iron": [
        "05",
        "06",
        "07",
        "08",
        "09",
        "10",
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
    ],
}

MC_MuonVars = [
    "CAEntryNo",
    "RunNo",
    "EventNo",
    "PrimaryID",
    "PrimaryE",
    "PrimaryTheta",
    "PrimaryPhi",
    "nModules",
    "nMuonLarge",
    "nMuonSmall",
    "MuonsLarge",
    "MuonsSmall",
]  #'CoreX', 'CoreY'

MC_ShowerVars = [
    "RunNo",
    "EventNo",
    "PrimaryID",
    "PrimaryEnergy",
    "Theta",
    "Phi",
    "CoreX",
    "CoreY",
    "nHitDetectors",
    "ISizeInside",
    "ISizeOutside",
    "Size",
    "PSum",
    "COGX",
    "COGY",
    "NKGFitFlag",
    "NKGStatus",
    "NKGLoop",
    "NKGX",
    "NKGY",
    "NKGZ",
    "NKGXerr",
    "NKGYerr",
    "NKGZerr",
    "NKGSize",
    "LnCerr",
    "Age",
    "Ageerr",
    "LnNKGP",
    "EDM",
    "Theta1",
    "Phi1",
    "ChiSq1",
    "TZero1",
    "Theta3",
    "Phi3",
    "Theta4",
    "Phi4",
    "Theta6",
    "Phi6",
    "nHitDetectorsOdd",
    "ThetaOdd1",
    "PhiOdd1",
    "ChiSqOdd1",
    "TZeroOdd1",
    "ThetaOdd3",
    "PhiOdd3",
    "ThetaOdd4",
    "PhiOdd4",
    "ThetaOdd6",
    "PhiOdd6",
    "nHitDetectorsEven",
    "ThetaEven1",
    "PhiEven1",
    "ChiSqEven1",
    "TZeroEven1",
    "ThetaEven3",
    "PhiEven3",
    "ThetaEven4",
    "PhiEven4",
    "ThetaEven6",
    "PhiEven6",
]  # ,\
#'nModules', 'nMuonLarge', 'MuonsLarge', 'nMuonSmall',\
#'MuonsSmall', 'nFourFold']

MC_ShowerPTVars = [
    "RunNo",
    "EventNo",
    "PrimaryID",
    "Theta",
    "Density",
    "nHitDetectors",
    "DetNo",
    "TOF",
    "PId",
    "Px",
    "Py",
    "Pz",
    "X",
    "Y",
]  #'PrimaryEnergy'


Data_ShowerVars = [
    "RunNo",
    "EventNo",
    "EvDate",
    "EvTime1",
    "EvTime2",
    "EvTimeFlag",
    "nHitDetectors",
    "PSum",
    "PSumIn",
    "PSumOut",
    "PSumRatio",
    "COGX",
    "COGY",
    "NKGX",
    "NKGY",
    "NKGZ",
    "NKGXerr",
    "NKGYerr",
    "NKGZerr",
    "LnCerr",
    "Ageerr",
    "NKGFitFlag",
    "NKGStatus",
    "NKGLoop",
    "NKGSize",
    "Age",
    "Size",
    "Energy",
    "LnNKGP",
    "EDM",
    "Theta1",
    "Phi1",
    "ChiSq1",
    "TZero1",
    "Theta3",
    "Phi3",
    "Theta4",
    "Phi4",
    "nHitDetectorsOdd",
    "ThetaOdd1",
    "PhiOdd1",
    "ChiSqOdd1",
    "TZeroOdd1",
    "ThetaOdd3",
    "PhiOdd3",
    "ThetaOdd4",
    "PhiOdd4",
    "nHitDetectorsEven",
    "ThetaEven1",
    "PhiEven1",
    "ChiSqEven1",
    "TZeroEven1",
    "ThetaEven3",
    "PhiEven3",
    "ThetaEven4",
    "PhiEven4",
    "nHitDetectorsLeft",
    "ThetaLeft1",
    "PhiLeft1",
    "ChiSqLeft1",
    "TZeroLeft1",
    "ThetaLeft3",
    "PhiLeft3",
    "ThetaLeft4",
    "PhiLeft4",
    "nHitDetectorsRight",
    "ThetaRight1",
    "PhiRight1",
    "ChiSqRight1",
    "TZeroRight1",
    "ThetaRight3",
    "PhiRight3",
    "ThetaRight4",
    "PhiRight4",
    "Theta6",
    "Phi6",
    "ThetaLeft6",
    "PhiLeft6",
    "ThetaRight6",
    "PhiRight6",
    "ThetaEven6",
    "PhiEven6",
    "ThetaOdd6",
    "PhiOdd6",
]

Data_MuonVars = [
    "RunNo",
    "EventNo",
    "EvDate",
    "EvTime1",
    "EvTime2",
    "EvMatchFlag",
    "MuRunNo",
    "MuEntryNo",
    "MuEvDate",
    "MuEvTime1",
    "MuEvTime2",
    "MuStatus",
    "ModuleFlag",
    "nMuonLarge",
    "MuonsLarge",
    "nMuonSmall",
    "MuonsSmall",
]

Data_ShowerPTVars = ["DetNo", "Density", "nHitDetectors", "TOF"]

MC_pathsmuon = {
    "gamma": "/fermion/users/common/GammaSim/QGSJET_FLUKA/mu_reco/",
    "proton": "/boson/users/common/Spect2.5/Set1/proton/MuDataAngle10/",
    "helium": "/boson/users/common/Spect2.5/Set1/helium/MuDataAngle10/",
    "nitrogen": "/boson/users/common/Spect2.5/Set1/nitrogen/MuDataAngle10/",
    "aluminium": "/boson/users/common/Spect2.5/Set1/aluminium/MuDataAngle10/",
    "iron": "/boson/users/common/Spect2.5/Set1/iron/MuDataAngle10/",
}

MC_pathsshower = {
    "gamma": "/fermion/users/common/GammaSim/QGSJET_FLUKA/",
    "proton": "/boson/users/common/Spect2.5/Set1/proton/",
    "helium": "/boson/users/common/Spect2.5/Set1/helium/",
    "nitrogen": "/boson/users/common/Spect2.5/Set1/nitrogen/",
    "aluminium": "/boson/users/common/Spect2.5/Set1/aluminium/",
    "iron": "/boson/users/common/Spect2.5/Set1/iron/",
}

MC_pathsshowerPT = {
    "gamma": "/fermion/users/common/GammaSim/QGSJET_FLUKA/",
    "proton": "/boson/users/common/Spect2.5/Set1/proton/",
    "helium": "/boson/users/common/Spect2.5/Set1/helium/",
    "nitrogen": "/boson/users/common/Spect2.5/Set1/nitrogen/",
    "aluminium": "/boson/users/common/Spect2.5/Set1/aluminium/",
    "iron": "/boson/users/common/Spect2.5/Set1/iron/",
}

MC_PSim = {"gamma": "/boson/users/dipti/CRAB_SIM_DB/EPOS/RECO_OUT/"}

MC_PSim_ShowerVars = [
    "RunNo",
    "EventNo",
    "PrimaryID",
    "PrimaryEnergy",
    "Theta",
    "Phi",
    "CoreX",
    "CoreY",
    "nHitDetectors",
    "ISizeInside",
    "ISizeOutside",
    "Size",
    "PSum",
    "COGX",
    "COGY",
    "NKGFitFlag",
    "NKGStatus",
    "NKGLoop",
    "NKGX",
    "NKGY",
    "NKGZ",
    "NKGXerr",
    "NKGYerr",
    "NKGZerr",
    "NKGSize",
    "LnCerr",
    "Age",
    "Ageerr",
    "LnNKGP",
    "EDM",
    "Theta1",
    "Phi1",
    "ChiSq1",
    "TZero1",
    "Theta3",
    "Phi3",
    "Theta4",
    "Phi4",
    "Theta6",
    "Phi6",
    "nHitDetectorsOdd",
    "ThetaOdd1",
    "PhiOdd1",
    "ChiSqOdd1",
    "TZeroOdd1",
    "ThetaOdd3",
    "PhiOdd3",
    "ThetaOdd4",
    "PhiOdd4",
    "ThetaOdd6",
    "PhiOdd6",
    "nHitDetectorsEven",
    "ThetaEven1",
    "PhiEven1",
    "ChiSqEven1",
    "TZeroEven1",
    "ThetaEven3",
    "PhiEven3",
    "ThetaEven4",
    "PhiEven4",
    "ThetaEven6",
    "PhiEven6",
    "nModules",
    "nMuonLarge",
    "MuonsLarge",
    "nMuonSmall",
    "MuonsSmall",
    "nFourFold",
]

MC_PSim_ShowerPTVars = [
    "RunNo",
    "EventNo",
    "PrimaryID",
    "PrimaryEnergy",
    "Theta",
    "Phi",
    "CoreX",
    "CoreY",
    "np",
    "nHitDetectors",
    "DetNo",
    "Density",
    "TOF",
    "PId",
    "Px",
    "Py",
    "Pz",
    "X",
    "Y",
]

MC_PSim_MuonVars = [
    "CAEntryNo",
    "RunNo",
    "EventNo",
    "PrimaryID",
    "PrimaryE",
    "PrimaryTheta",
    "PrimaryPhi",
    "CoreX",
    "CoreY",
    "nModules",
    "nMuonLarge",
    "nMuonSmall",
    "MuonsLarge",
    "MuonsSmall",
]
